name: Snapyr CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11.3

    steps:
      - uses: actions/checkout@v2
      - run: echo "configuring to use Xcode 12.5"
        env:
          DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer
      - run: make build-ios
      - run: make test-ios
      - run: make lint
      - run: make carthage
