name: Snapyr CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v2
      - run: echo "configuring to use Xcode 13.2.1"
        env:
          DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer
      - run: make clean
      - run: make build-ios
      - run: make test-ios
      - run: make lint
      - run: make carthage
      - run: make archive
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEV_S3_SAMPLE_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEV_S3_SAMPLE_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws s3 cp  ./builtframework/Snapyr.xcframework.zip s3://sample-apps.snapyrdev.com/ios/ --acl public-read
