name: Snapyr Publish

on: 
  workflow_dispatch:
    inputs:
      Version:
        description: 'Version'     
        required: true

jobs:
  build:

    runs-on: macos-11.3

    steps:
      - uses: actions/checkout@v2
      - run: echo "configuring to use Xcode 12.5"
        env:
          DEVELOPER_DIR: /Applications/Xcode_12.5.app/Contents/Developer
      - run: make build-ios
      - run: make test-ios
      - run: make lint
      - run: make carthage
      - run: make archive
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Snapyr.framework.zip 
          name: Snapyr.framework.${{ github.event.inputs.version }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


